import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter } from '../components/contract';
import Navbar from './components/Navbar';
import { Button, Center, Container, Link } from '@chakra-ui/react';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Claim</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <Navbar />

      <Container>
        <Center>
          <Link href="/auth"> 
            <Button marginTop="10rem" >
              Sign In
            </Button>
          </Link>
        </Center>
      </Container>
    </div>
  );
}
